name: snapcraft

on:
  push:
    branches:
      - master

jobs:
  stable:

    runs-on: ubuntu-18.04
    container:
      image: sirredbeard/snap-build

    steps:
    - uses: actions/checkout@v1
    - name: Upgrade Snapcraft Docker container to Bionic to get qml-module-qtwebengine
      run: |
        sudo sed -i 's/bionic/focal/g' /etc/apt/sources.list
        sudo apt update
        sudo apt -y dist-upgrade
        sudo apt -y install dpkg-dev
    - name: Build .snap
      run: |
        snapcraft    
    - name: Push .snap to Snapcraft.io
      env:
        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
      run: |
        mkdir .snapcraft
        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
        snapcraft push --release=stable *.snap

  #beta:

#    runs-on: ubuntu-18.04
#    container:
#      image: snapcore/snapcraft

#    steps:
#    - uses: actions/checkout@v1
#    - name: Upgrade Snapcraft Docker container to Eoan to get qml-module-qtwebengine
#      run: |
#        sudo sed -i 's/xenial/disco/g' /etc/apt/sources.list
#        sudo apt update
#        sudo apt -y dist-upgrade
#        sudo apt-get -y install wget
#    - name: Build .snap
#      run: |
#        snapcraft    
#    - name: Push .snap to Snapcraft.io
#      env:
#        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
#      run: |
#        cd snap
#        mkdir .snapcraft
#        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
#        snapcraft push --release=beta *.snap

#  edge:

#    runs-on: ubuntu-18.04
#    container:
#      image: snapcore/snapcraft

#    steps:
#    - uses: actions/checkout@v1
#    - name: Upgrade Snapcraft Docker container to Focal to get qml-module-qtwebengine
#      run: |
#        sudo sed -i 's/xenial/focal/g' /etc/apt/sources.list
#        sudo apt update
#        sudo apt -y dist-upgrade
#    - name: Build .snap
#      run: |
#        snapcraft    
#    - name: Push .snap to Snapcraft.io
#      env:
#        SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
#      run: |
#        cd snap
#        mkdir .snapcraft
#        echo ${SNAPCRAFT_LOGIN_FILE} | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
#        snapcraft push --release=edge *.snap
